# Generated by Django 5.2.15 on 2026-06-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dataset_id', models.IntegerField(blank=True, null=True)),
                ('ms_sub_class', models.IntegerField()),
                ('ms_zoning', models.CharField(max_length=20)),
                ('lot_frontage', models.FloatField(blank=True, null=True)),
                ('lot_area', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=50)),
                ('overall_qual', models.IntegerField()),
                ('overall_cond', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('year_remod_add', models.IntegerField()),
                ('gr_liv_area', models.IntegerField()),
                ('full_bath', models.IntegerField()),
                ('half_bath', models.IntegerField()),
                ('bedroom_abv_gr', models.IntegerField()),
                ('kitchen_abv_gr', models.IntegerField()),
                ('kitchen_qual', models.CharField(max_length=20)),
                ('tot_rms_abv_grd', models.IntegerField()),
                ('total_bsmt_sf', models.IntegerField()),
                ('bsmt_qual', models.CharField(max_length=30)),
                ('garage_type', models.CharField(max_length=30)),
                ('garage_cars', models.IntegerField()),
                ('garage_area', models.IntegerField()),
                ('fireplaces', models.IntegerField()),
                ('sale_condition', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
