# Generated by Django 5.2.15 on 2026-06-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='model_input_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
